#!/bin/sh

# Set these paths appropriately

BIN=/home/docio/git/AutoPhrase/tools/treetagger/bin
CMD=/home/docio/git/AutoPhrase/tools/treetagger/cmd
LIB=/home/docio/git/AutoPhrase/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
TAGGER=tree-tagger
ABBR_LIST=${LIB}/portuguese-abbreviations-utf8
PARFILE=${LIB}/portuguese2-utf8.par

$TOKENIZER -p -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
