#!/bin/sh

# Set these paths appropriately

BIN=/home/docio/git/AutoPhrase/tools/treetagger/bin
CMD=/home/docio/git/AutoPhrase/tools/treetagger/cmd
LIB=/home/docio/git/AutoPhrase/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize-korean.pl
PARFILE=${LIB}/korean-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE |
$CMD/add-korean-sentence-markers.pl |
$CMD/reformat-korean-tagger-output.pl
